# Generated by Django 4.1 on 2022-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_info_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_info',
            old_name='name',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='account_info',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
